### ISSUE TITLE
Alterar nome do projeto no repositório do Github para aderir a nova nomenclatura. 

### ISSUE THREAD

**Issue by brunousml** [scieloorg/inbox#48]
Já incorporamos no nome inbox para os diretórios do projeto e precisamos efetuar a mudança para a denominação do repositório também no github. 

Gostaria de entender a estratégia que pretendem seguir:
- Alterar o nome deste
- criar um novo com nome atualizado

**Comment by gustavofonseca** [comment]
Acho que podemos renomear esse

**Comment by gustavofonseca** [comment]
[Continuação].. para ``inbox``, sem o sufixo ``-core``.

**Comment by gustavofonseca** [comment]
Feito.
