### ISSUE TITLE
Ajuste de permissões para /app/static

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/inbox#78]
O diretório /app/static é construído no momento de inicialização do container, testar o acesso via volume-from e aplicar o uso em caso de sucesso.

**Comment by brunousml** [comment]
@fabiobatalha achas que posso incluir no escopo dessa tarefa, a remoção do docker volume inbox-django-media, e setar no compose para que ele utilize um ponto de montagem no host?

**Comment by fabiobatalha** [comment]
@brunousml 

Acho que sim.
