### ISSUE TITLE
Configurações de Nginx para aceitar arquivos maiores

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/inbox#79]
Aumentar a capacidade de upload de arquivos no Nginx.

**Comment by brunousml** [comment]
Aqui devo setar um valor específico ou garantir que não haverá limites para o upload de arquivos?

**Comment by fabiobatalha** [comment]
Tem que ter um limite, só não sei dizer qual, mas podemos pedir para o pessoal o tamalho dos pacotes que elas recebem.

Poderia verificar se no nginx é possível limitar o IP do POST para o IP do inbox-shell, neste caso poderíamos deixar ilimitado.

Mas por hora podemos aumentar para um valor maior temporário (100Mb) e estudar o caso.

**Comment by brunousml** [comment]
Segundo informações fornecidas pela Jennifer o SciELO recebe, eventualmente, pacotes de até 6gb. Segundo histórico de depósitos.

**Comment by fabiobatalha** [comment]
Senhores, que tal por hora, configurarmos um limite que atenda algo como 90% da demanda, assim teremos tempo de pensar em algo, abrindo um outro ticket para discussão.

* Acho que podemos setar um limit para um valor que atenda 80% das reqs
* Configurar timeout para 0 
Ambas configurações apenas para o endpoint de depósito, se isso for possível.

**Comment by brunousml** [comment]
O que achas de setar pra 1000mb?
