### ISSUE TITLE
Incluir parametro para configuração de nível de log do gunicorn.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/inbox#81]
em gunicorn.sh

Ajustar os parâmetros para produção de logs de acordo com nível de log configurado

/usr/local/bin/gunicorn config.wsgi -w 4 -b 0.0.0.0:5000 --chdir=/app

O parâmetro deve ser configurado a partir de uma variável de ambiente incluída no docker-compose e utilizar INFO como default.

**Comment by brunousml** [comment]
Em relação a nomenclatura dessa variável de ambiente, minha sugestão é `DJANGO_LOGGING_LEVEL`.

O que acham?
